name: harvey_ai_infra_assignment
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - flask
  - pandas
  - beautifulsoup4
  - faiss-cpu=1.8.0
  - pip:
    - selenium
    - undetected_chromedriver
    - webdriver_manager
    - pymupdf
    - langchain
    - spacy
    - spacy-lookups-data
    - en-core-web-sm@https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0.tar.gz#egg=en_core_web_sm

